#!/usr/bin/env zsh
#
# Setup PHPUnit testing environment for MSC Stealth Login
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
TEST_DIR="/tmp/msc-testing"
TESTS_LIB_DIR="$TEST_DIR/wordpress-tests-lib"

echo "=============================================="
echo "MSC Stealth Login - Test Setup"
echo "=============================================="

# Check if composer is available
if ! command -v composer >/dev/null 2>&1; then
    echo "ERROR: composer not found. Please install Composer first."
    exit 1
fi

# Check if svn is available
if ! command -v svn >/dev/null 2>&1; then
    echo "ERROR: svn not found. Please install Subversion first."
    exit 1
fi

echo ""
echo "Step 1: Installing composer dependencies..."
echo "--------------------------------------------"
cd "$PLUGIN_DIR"
composer install --no-interaction

echo ""
echo "Step 2: Setting up WordPress test suite..."
echo "--------------------------------------------"

# Create test directory
mkdir -p "$TEST_DIR"

# Check if WordPress tests already exist
if [[ -d "$TESTS_LIB_DIR" ]]; then
    echo "WordPress test suite already exists at $TESTS_LIB_DIR"
    read -q "REPLY?Update to latest version? [y/N] "
    echo ""
    if [[ "${REPLY:-n}" =~ ^[Yy]$ ]]; then
        echo "Updating WordPress test suite..."
        cd "$TESTS_LIB_DIR"
        svn update
        cd "$TEST_DIR/wordpress-tests-data" 2>/dev/null && svn update
        cd "$TEST_DIR/wordpress-develop/src" 2>/dev/null && svn update
    fi
else
    echo "Downloading WordPress test suite..."
    cd "$TEST_DIR"

    echo "  - Downloading test includes..."
    svn checkout https://develop.svn.wordpress.org/trunk/tests/phpunit/includes/ wordpress-tests-lib

    echo "  - Downloading test data..."
    svn checkout https://develop.svn.wordpress.org/trunk/tests/phpunit/data/ wordpress-tests-data

    echo "  - Downloading WordPress source..."
    svn checkout https://develop.svn.wordpress.org/trunk/src/ wordpress-develop/src
fi

echo ""
echo "Step 3: Creating wp-tests-config.php..."
echo "--------------------------------------------"

CONFIG_FILE="$TEST_DIR/wp-tests-config.php"

# Detect PHP binary
PHP_BINARY=$(command -v php)

# Detect MySQL credentials
echo ""
echo "MySQL Configuration:"
echo "-------------------"
read -p "Database name [wordpress_test]: " DB_NAME
DB_NAME="${DB_NAME:-wordpress_test}"

read -p "Database user [root]: " DB_USER
DB_USER="${DB_USER:-root}"

read -s -p "Database password []: " DB_PASSWORD
echo ""

read -p "Database host [localhost]: " DB_HOST
DB_HOST="${DB_HOST:-localhost}"

# Create config file
cat > "$CONFIG_FILE" << EOF
<?php
/**
 * WordPress Test Suite Configuration
 *
 * Generated by setup-tests.sh
 */

// PHP binary path.
define( 'WP_PHP_BINARY', '${PHP_BINARY}' );

// Test database settings.
define( 'DB_NAME', '${DB_NAME}' );
define( 'DB_USER', '${DB_USER}' );
define( 'DB_PASSWORD', '${DB_PASSWORD}' );
define( 'DB_HOST', '${DB_HOST}' );
define( 'DB_CHARSET', 'utf8' );
define( 'DB_COLLATE', '' );

// Test domain.
define( 'WP_TESTS_DOMAIN', 'example.org' );
define( 'WP_TESTS_EMAIL', 'admin@example.org' );
define( 'WP_TESTS_TITLE', 'Test Blog' );

// Test credentials.
define( 'WP_TESTS_NETWORK', false );
define( 'WP_TESTS_NETWORK_TITLE', 'Test Network' );
define( 'WP_TESTS_NETWORK_ADMIN', 'network@example.org' );
define( 'WP_TESTS_SUBDOMAIN_INSTALL', false );

// Test salts.
define( 'AUTH_KEY', 'put your unique phrase here' );
define( 'SECURE_AUTH_KEY', 'put your unique phrase here' );
define( 'LOGGED_IN_KEY', 'put your unique phrase here' );
define( 'NONCE_KEY', 'put your unique phrase here' );
define( 'AUTH_SALT', 'put your unique phrase here' );
define( 'SECURE_AUTH_SALT', 'put your unique phrase here' );
define( 'LOGGED_IN_SALT', 'put your unique phrase here' );
define( 'NONCE_SALT', 'put your unique phrase here' );

// Content directories.
define( 'WP_CONTENT_DIR', '${TEST_DIR}/wordpress-develop/src/wp-content' );
define( 'WP_CONTENT_URL', 'http://example.org/wp-content' );
define( 'ABSPATH', '${TEST_DIR}/wordpress-develop/src/' );

// Table prefix.
$table_prefix = 'wptests_';

// Debug mode.
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
define( 'WP_DEBUG_DISPLAY', false );

// Memory limit.
ini_set( 'memory_limit', '-1' );
EOF

echo "Config file created at: $CONFIG_FILE"

echo ""
echo "Step 4: Creating database..."
echo "--------------------------------------------"
if command -v mysql >/dev/null 2>&1; then
    echo "Creating database '${DB_NAME}'..."
    mysql -u "${DB_USER}" ${DB_PASSWORD:+-p"${DB_PASSWORD}"} -h "${DB_HOST}" -e "CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" 2>/dev/null || echo "Could not create database. Please create it manually."
else
    echo "MySQL command not found. Please create the database manually:"
    echo "  CREATE DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
fi

echo ""
echo "=============================================="
echo "Setup Complete!"
echo "=============================================="
echo ""
echo "To run the tests:"
echo ""
echo "  cd $PLUGIN_DIR"
echo "  WP_TESTS_DIR=$TESTS_LIB_DIR vendor/bin/phpunit --testdox"
echo ""
echo "Or with coverage:"
echo ""
echo "  WP_TESTS_DIR=$TESTS_LIB_DIR vendor/bin/phpunit --coverage-html coverage"
echo ""
echo "See tests/README.md for more information."
